### PR TITLE
EXT-1863: Keep the NuxtJS layout equal to the NextJS

### PR DESCRIPTION
**Pull request by demetriusfeijoo**
Issue: EXT-1863

### What?
Adjust the NuxtJS starter example to look the same as the NextJS. So, minors layout changes were made such as:

- A subtitle was added;
- Header's margins/paddings were adjusted;

### Before

"Desktop" version
image

"Mobile" version
image

### After

"Desktop" version
image

"Mobile" version
image

### CODE REVIEW

**Review by eunjae-lee — APPROVED** [review]
Awesome! You showed this to me yesterday, and it'd be even better if you could include some screenshots for other people viewing this PR :)

**Comment by demetriusfeijoo** [comment]
Thanks for reviewing and for the screenshot suggestion @eunjae-lee. 

It'd be really nice, indeed!

I'll update the PR's description and add the screenshots.

**Comment by eunjae-lee** [comment]
@demetriusfeijoo I'm sorry but could you also include "before" images ? :)

**Comment by demetriusfeijoo** [comment]
> @demetriusfeijoo I'm sorry but could you also include "before" images ? :)

**Comment by demetriusfeijoo** [comment]
Sure, @eunjae-lee. 

It's done! 

I edited the PR's description with the screenshots since it may be better being there.

**Comment by eunjae-lee** [comment]
@demetriusfeijoo thanks! this is awesome. let's merge it ! :)

**Pull request merged**
